name: build
run-name: ${{ github.head_ref }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: cd ${{ github.workspace }} 
      - name: Print the current directory
        run: ls
