name: build
run-name: ${{ github.head_ref }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: cd ${{ github.workspace }} 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # update the Node version to meet your needs
          node-version: 20
          cache: npm
      - name: Build App
        run: |
          next build
      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          repository-name: pnegus/pnegus.github.io

